# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepost',
            old_name='title',
            new_name='birth_from',
        ),
        migrations.RemoveField(
            model_name='homepost',
            name='text',
        ),
        migrations.AddField(
            model_name='homepost',
            name='career',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='education',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='job',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='p_laguage',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='ph_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='w_experience',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
