# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170830_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='profile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
