# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('birth_from', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=200)),
                ('planguage', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('wexperience', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
